###
POST http://localhost:8080/api/user/register
Content-Type: application/json

{
  "name": "Alex",
  "username": "Alex19",
  "email": "alex@example.ro",
  "password": "password1234"
}

###
GET http://localhost:8080/api/user/users

###
GET http://localhost:8080/api/user/users/1

###
PATCH http://localhost:8080/api/user/users/1
Content-Type: application/json

{
  "name": "Dana",
  "username": "Dana1960",
  "email": "dana@example.ro",
  "password": "password98765"
}

###
DELETE http://localhost:8080/api/user/users/1